# Generated by Django 4.1.7 on 2023-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizationalAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothes",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="clothes",
            name="i_buy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clothes",
            name="brand",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
