# Generated by Django 4.1.7 on 2023-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizationalAPP", "0003_rename_i_buy_clothes_when_both_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothes",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
