# Generated by Django 4.2 on 2023-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0005_alter_clothes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='when_both',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
