# Generated by Django 4.1.7 on 2023-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizationalAPP",
            "0008_marketplaces_clothes_predicted_sale_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="marketplaces",
            field=models.ManyToManyField(
                blank=True, null=True, to="organizationalAPP.marketplaces"
            ),
        ),
    ]
