# Generated by Django 4.2 on 2023-05-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0010_clothes_sell_statute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='cloth_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizationalAPP.clothsubtype'),
        ),
    ]
