# Generated by Django 4.2 on 2023-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0011_clothsubtype_clothes_cloth_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='condition',
            field=models.IntegerField(default=5),
        ),
    ]
