# Generated by Django 4.1.7 on 2023-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizationalAPP", "0013_sizes_clothtype_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothtype",
            name="size",
        ),
        migrations.AlterField(
            model_name="clothes",
            name="marketplaces",
            field=models.ManyToManyField(
                blank=True, to="organizationalAPP.marketplaces"
            ),
        ),
    ]
