# Generated by Django 4.1.7 on 2023-06-03 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizationalAPP", "0015_clothtype_cloth_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothtype",
            old_name="cloth_type",
            new_name="measurement",
        ),
    ]
