# Generated by Django 4.2 on 2023-06-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0016_rename_cloth_type_clothtype_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothtype',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='clothtype',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizationalAPP.sizes'),
        ),
    ]
