# Generated by Django 4.2 on 2023-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0017_clothtype_slug_alter_clothtype_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothtype',
            name='measurement',
        ),
        migrations.AddField(
            model_name='clothtype',
            name='measurement',
            field=models.ManyToManyField(blank=True, null=True, to='organizationalAPP.sizes'),
        ),
    ]
