# Generated by Django 4.2 on 2023-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0018_remove_clothtype_measurement_clothtype_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
