# Generated by Django 4.2 on 2023-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0019_alter_clothes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='cm_value',
            field=models.IntegerField(default=0),
        ),
    ]
