# Generated by Django 4.2 on 2023-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0020_sizes_cm_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='overall',
            field=models.IntegerField(default=0),
        ),
    ]
