# Generated by Django 4.2 on 2023-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0021_sizes_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
