# Generated by Django 4.2 on 2023-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalAPP', '0022_alter_clothes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothtype',
            name='measurement',
            field=models.ManyToManyField(blank=True, to='organizationalAPP.sizes'),
        ),
    ]
